apiVersion: v1
kind: Pod  # 资源类型为Pod
metadata:
  name: nginx-pod  # Pod的名称
  labels:
    app: nginx  # 标签为nginx
spec:
  containers:
  - name: nginx-container  # 容器名称为nginx-container
    image: nginx:latest  # 使用Nginx最新版本的镜像
    ports:
    - containerPort: 80  # 容器内部的端口为80
    imagePullPolicy: IfNotPresent  # 当目标镜像不存在时才拉取
